apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: node
  template:
    metadata:
      name: frontend
      labels:
        tier: front
        app: node
        version: v1
    spec:
      containers:
        - name: frontend
          image: schoolofdevops/frontend:latest
          ports:
            - containerPort: 8079
              protocol: TCP
