apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend-blue
  namespace: mogambo
spec:
  replicas: 5
  strategy:
    type: Recreate
  minReadySeconds: 40
  revisionHistoryLimit: 4
  paused: false
  template:
    metadata:
      name: frontend
      labels:
        tier: "1"
        app: frontend
        env: dev
        release: bluegreen
        code: blue
    spec:
      containers:
        - name: frontend
          image: schoolofdevops/frontend:v3.0
          ports:
            - containerPort: 8079
              protocol: TCP
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
