kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: catalogue-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
