apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend
  namespace: mogambo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 40
  revisionHistoryLimit: 4
  paused: false
  template:
    metadata:
      name: frontend
      labels:
        tier: "1"
        app: frontend
        env: dev
        version: v1.0
    spec:
      containers:
        - name: frontend
          image: schoolofdevops/frontend:v1.0
          ports:
            - containerPort: 8079
              protocol: TCP
          env:
            - name: NODE_ENV
              valueFrom: 
                configMapKeyRef:
                  name: frontend
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: frontend
                  key: PORT
