---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
  namespace: mogambo
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: frontend-blue

  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
