apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend-canary
  namespace: mogambo
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 40
  revisionHistoryLimit: 4
  paused: false
  template:
    metadata:
      name: frontend
      labels:
        tier: "1"
        app: frontend
        env: dev
        release: canary
    spec:
      containers:
        - name: frontend
          image: schoolofdevops/frontend:v2.0
          ports:
            - containerPort: 8079
              protocol: TCP
