apiVersion: v1
kind: Pod
metadata:
  name: ghost
  labels:
    app: ghost
    tier: front
    version: latest
spec:
  containers:
    - name: app
      image: ghost:0-alpine
      ports:
        - containerPort: 2368
          protocol: TCP
