apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    tier: back
    app: db
    version: 8
spec:
  containers:
    - name: mysql
      image: mysql:8
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: dfgk8923Jsk89JJSsdlf
        - name: MYSQL_DATABASE
          value: ghost
        - name: MYSQL_USER
          value: ghostapp
        - name: MYSQL_PASSWORD
          value: skljlj230kHshk02Ksc
      volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
  volumes:
    - name: db-data
      hostPath:
        path: /var/lib/mysql
        type: DirectoryOrCreate
