apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend-green
  namespace: mogambo
spec:
  replicas: 5
  strategy:
    type: Recreate
  minReadySeconds: 40
  revisionHistoryLimit: 4
  paused: false
  template:
    metadata:
      name: frontend
      labels:
        tier: "1"
        app: frontend
        env: dev
        release: bluegreen
        code: green
    spec:
      containers:
        - name: frontend
          image: schoolofdevops/frontend:v1.0
          ports:
            - containerPort: 8079
              protocol: TCP
