apiVersion: v1
kind: Service
metadata:
  name: catalogue-db
  namespace: mogambo
spec:
  selector:
    app: catalogue-db
    env: dev
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
