apiVersion: v1
kind: Pod
metadata:
  name: catalogue-db
  labels:
    app: catalogue-db
    env: dev
    version: latest
    tier: "3"
spec:
  containers:
    - name: catalogue-db
      image: schoolofdevops/catalogue-db:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: dfgk8923Jsk89JJSsdlf
        - name: MYSQL_DATABASE
          value: socksdb
        - name: MYSQL_USER
          value: catalogue_user
        - name: MYSQL_PASSWORD
          value: default_password
      volumeMounts:
        - name: catalogue-db-vol
          mountPath: /var/lib/mysql

  volumes:
    - name: catalogue-db-vol
      persistentVolumeClaim:
        claimName: catalogue-db-pvc
