apiVersion: v1
kind: Deployment
metadata:
  name: db
  namespace: ghost
spec:
  replicas: 1
  template:
    metadata:
      name: db
      label:
        app: db
  spec:
    containers:
      - name: db
        image: mysql:5.7
        ports:
          - containerPort: 3306
            protocol: TCP
